#!/bin/sh

RESET=$(printf "\033[0m")
RED=$(printf "\033[91m")
YELLOW=$(printf "\033[93m")
GREEN=$(printf "\033[92m")
CYAN=$(printf "\033[96m")
BLUE=$(printf "\033[94m")
MAGENTA=$(printf "\033[95m")
WHITE=$(printf "\033[97m")

echo "${CYAN}Welcome to ${RESET}${MAGENTA}Linux $(uname -r) $(uname -m)${RESET}${CYAN}!${RESET}"

for i in networking install_packages;do
    /etc/init.d/${i}
done

echo "Uptime:$(cat /proc/uptime|cut -d ' ' -f 1)s"

while :;do
    cat /etc/motd
    setsid cttyhack $(cat /etc/passwd|grep root|cut -f 7 -d ":") --login
    while :;do
        case $(dialog --menu "Exit" 20 50 10 1 "Reboot" 2 "Poweroff" 3<&2 2<&1 1<&3) in
            1) reboot
            ;;
            2) poweroff
            ;;
            *) break
            ;;
        esac
    done
done
