name: Run fastfetch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get fastfetch
      run: |
        whoami
        wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.15.0/fastfetch-linux-amd64.deb
        apt install ./fastfetch-linux-amd64.deb
    - name: Run fastfetch
      run: |
        fastfetch -c /usr/share/fastfetch/presets/all.jsonc                                                                                                                          ✔  at 17:40:44  

