name: Run fastfetch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get fastfetch
      run: |
        curl -L https://github.com/fastfetch-cli/fastfetch/releases/download/2.15.0/fastfetch-linux-amd64.deb > fastfetch.deb
        sudo apt-get install ./fastfetch.deb
    - name: Run fastfetch
      run: |
        fastfetch -c /usr/share/fastfetch/presets/all.jsonc
