name: Compile Linux Kernel
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential llvm lld clang clang-tools libncurses-dev bison flex libssl-dev libelf-dev
    - name: Compile Busybox
      run: |
        BUSYBOX_VERSION=1.36.1
        curl https://busybox.net/downloads/busybox-${BUSYBOX_VERSION}.tar.bz2 | tar -jx
        pushd busybox-${BUSYBOX_VERSION}
        make defconfig
        LDFLAGS="--static" make -j$(nproc)
        du -k busybox
        popd
    - name: Compile Kernel
      run: |
        KERNEL_VERSION=6.6.69
        curl https://cdn.kernel.org/pub/linux/kernel/v${KERNEL_VERSION%%.*}.x/linux-${KERNEL_VERSION}.tar.xz | tar -Jx
        pushd linux-${KERNEL_VERSION}
        make LLVM=1 defconfig  
        sed -i "s|.*\\(CONFIG_KERNEL_.*\\)=y|\\#\\ \\1 is not set|" .config
        # sed -i "s|.*# CONFIG_KERNEL_XZ is not set.*|CONFIG_KERNEL_XZ=y|" .config
        sed -i "s|^CONFIG_DEBUG_KERNEL.*|# CONFIG_DEBUG_KERNEL is not set|" .config
        sed -i "s|.*CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y.*|# CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE is not set|" .config
        sed -i "s|.*# CONFIG_CC_OPTIMIZE_FOR_SIZE is not set.*|CONFIG_CC_OPTIMIZE_FOR_SIZE=y|" .config
        sed -i "s|.*CONFIG_AUDIT=y.*|# CONFIG_AUDIT is not set|" .config
        sed -i "s|.*CONFIG_PROFILING=y.*|# CONFIG_PROFILING is not set|" .config
        sed -i "s|.*CONFIG_FB_VESA.*|CONFIG_FB_VESA=y|" .config
        make LLVM=1 -j$(nproc)
        cp arch/x86/boot/bzImage ../vmlinuz
        popd
    - run: du -k vmlinuz
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vmlinuz
        path: vmlinuz
