name: Release ArchLingmo ISO

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 1 * *'

jobs:
  release-archlingmo-iso:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Download Artifact
      id: download-artifact
      run: |
        REPO="LingmoOS/archlingmo-archiso-config"
        LATEST_RUN_ID=$(curl -s \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/$REPO/actions/runs \
          | jq '.workflow_runs | map(select(.status == "completed")) | first | .id')
        ARTIFACT_ID=$(curl -s \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/$REPO/actions/runs/${LATEST_RUN_ID}/artifacts \
          | jq '.artifacts | first | .id')
        curl -L \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/$REPO/actions/artifacts/${ARTIFACT_ID}/zip \
          -o artifact.zip

    - name: List files in artifact
      run: |
        unzip artifact.zip
        7z l *.iso

    - name: Split Artifact
      run: 7z a -tzip -v2097151k archlingmo.zip *.iso
        
    - name: Get the current date
      run: echo "RELEASE_DATE=$(date +'%Y.%m.%dT%H:%M')" >> $GITHUB_ENV
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: archlingmo.zip*
          tag_name: "${{ env.RELEASE_DATE }}"
