name: Release ArchLingmo ISO

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 1 * *'

jobs:
  release-archlingmo-iso:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Run ID
      id: get-run-id
      run: |
        REPO="LingmoOS/archlingmo-archiso-config"
        RUN_ID=$(curl -s \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/$REPO/actions/runs \
          | jq '.workflow_runs | map(select(.status == "completed")) | first | .id')
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
      
    - name: Download Artifact
      id: download-artifact
      uses: actions/download-artifact@v4
      with:
        repository: LingmoOS/archlingmo-archiso-config
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ env.RUN_ID }}
        path: .

    - name: List files in artifact
      run: 7z l archiso/*.iso
        
    - name: Get the current date
      run: echo "RELEASE_DATE=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: archiso/*.iso
          tag_name: "${{ env.RELEASE_DATE }}"
