name: Release ArchLingmo ISO

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 1 * *'

jobs:
  release-archlingmo-iso:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Download Artifact
      id: download-artifact
      uses: actions/download-artifact@v4
      with:
        repository: LingmoOS/archlingmo-archiso-config
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path: .

    - name: List files in artifact
      run: 7z l *.iso

    - name: Split Artifact
      run: 7z a -tzip -v2097151k archlingmo.zip *.iso
        
    - name: Get the current date
      run: echo "RELEASE_DATE=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: archlingmo.zip*
          tag_name: "${{ env.RELEASE_DATE }}"
