#!/bin/ash

if [ $$ -ne 1 ];then
    echo "$0: must be run as PID 1"
    exit 1
fi

printf "Mounting /dev /proc /sys /dev/pts /dev/shm... "
touch /dev/null
mount -t devtmpfs dev /dev &
mount -t proc proc /proc &
mount -t sysfs sys /sys &
wait
mkdir /dev/pts
mkdir /dev/shm
mount -t devpts devpts /dev/pts &
mount -t tmpfs tmpfs /dev/shm -o rw &
wait
echo "Done"

for i in $(cat /proc/cmdline);do
    case $i in
        init=/init|init=init)
            :;;
        init=*)
            exec ${i#init=};;
    esac
done

/etc/init.d/rcS

while :;do sleep 1d;done
